
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: backstage-db
    restart: always
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backstage:
    build: .
    container_name: backstage-app
    restart: always
    ports:
      - "7007:7007"
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DATABASE: backstage
      APP_CONFIG_backend_database_client: pg
      APP_CONFIG_backend_database_connection_host: postgres
      APP_CONFIG_backend_database_connection_user: backstage
      APP_CONFIG_backend_database_connection_password: backstage
      APP_CONFIG_backend_database_connection_database: backstage
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      JENKINS_BASIC_AUTH: ${JENKINS_BASIC_AUTH}
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres_data:
