
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Servicio Python generado automáticamente
  tags:
    - python
    - servicio
  annotations:
    github.com/project-slug: ${{ values.repoUrl | parseRepoUrl }}
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
